import type { DashaPhal, NavagrahaEn } from "src/backend/types";

export const MahaDashaPhal: Record<NavagrahaEn, DashaPhal> = {
    Sun: {
        BPHS: {
            english:
                "During the Dasa of Sun there is acquisition of wealth, great felicity and honours from the Government, if at the time of birth Sun is in his own Rasi, in his exaltation Rasi, in a Kendra, in Labh, be associated with the Lord of Dharm, or the Lord of Karm and strong in his Varg. The native will be blessed with a son (children), if Sun is with the Lord of Putr. The native will acquire elephants and other kinds of wealth, if Sun is associated with the Lord of Dhana. The native will enjoy comforts of conveyances, if Sun is associated with the Lord of Bandhu. He attains a high position, like that of Army Chief, by the beneficence of the king and enjoys all kinds of happiness. Thus during the Dasa of a strong (and favourable) Sun there are acquisitions of clothes, agricultural products, wealth, honours, conveyances etc.  During the Dasa of Sun there will be anxieties, loss of wealth, punishment from Government, defamation, opposition by kinsmen, distress to father, (in)auspicious happenings at home, distress to paternal and maternal uncles etc., anxiety and inimical relations with other people for no reason whatsoever, should Sun be in his Rasi of debilitation, be weak in Ari, Randhra, or Vyaya, or be associated with malefic Grahas, or with the Lord of Ari, Randhra, or Vyaya. There will be some favourable effects at times, if in the above situations Sun receives a Drishti from benefic Grahas. The effects will always be unfavourable, when malefic Grahas give a Drishti to Sun.",
            hindi: "सूर्य के दास के दौरान सरकार से धन, महान प्रसन्नता और सम्मान की प्राप्ति होती है, यदि जन्म के समय सूर्य अपनी राशि में होता है, तो उसके उत्थान में राशी, एक केंद्र में, लाभ में, धर्म के भगवान, या कर्म के भगवान के साथ जुड़ा होता है और अपने कर्ग में मजबूत होता है। यदि सूर्य पुत्र के प्रभु के साथ है, तो जातक को पुत्र (संतान) का आशीर्वाद मिलेगा। यदि सूर्य धना के भगवान के साथ जुड़ा हुआ है, तो जातक हाथी और अन्य प्रकार की संपत्ति प्राप्त करेगा। यदि सूर्य बंधु के प्रभु के साथ जुड़ा हुआ है, तो जातक को आवागमन की सुख - सुविधाओं का आनंद मिलेगा। वह राजा के उपकार से सेना प्रमुख की तरह एक उच्च पद प्राप्त करता है और सभी प्रकार की खुशी का आनंद लेता है। इस प्रकार एक मजबूत (और अनुकूल) सूर्य के दास के दौरान कपड़े, कृषि उत्पाद, धन, सम्मान, संपदा आदि का अधिग्रहण होता है। सूर्य के दास के दौरान चिंताएं, धन की हानि, सरकार से दंड, मानहानि, रिश्तेदारों का विरोध, पिता के लिए संकट, (घर में)शुभ घटनाएं, पितृ और मामा आदि के लिए संकट, बिना किसी कारण के अन्य लोगों के साथ चिंता और शत्रुतापूर्ण संबंध, क्या सूर्य को अपने दुर्बलता के राशी में होना चाहिए, अरी, रणध्रा, या व्याया में कमजोर होना चाहिए, या दुष्ट ग्रहों से जुड़ा होना चाहिए, या अरी, रणध्रा, या व्याया के भगवान के साथ होना चाहिए। कभी - कभी कुछ अनुकूल प्रभाव होंगे, यदि उपरोक्त स्थितियों में सूर्य को लाभकारी ग्रहों से दृष्टि प्राप्त होती है। प्रभाव हमेशा प्रतिकूल होगा, जब दुर्भावनापूर्ण ग्रह सूर्य को दृष्टि देते हैं।",
        },
        JatakaParijata: {
            english:
                "Sloka 60. During the progress of the Sun's dasa, the general effects to be noted will be: money-making by stealthy mining and other ways, trouble from fire and beasts, inflammation of the eyes, illness affecting the stomach and teeth, separation from wife and children, loss among reverend seniors and parents and general decay among servants, kine and property.  Sloka 71. In the initial portion of the Sun's dasa, the father of the person concerned will fall ill, and there will be much expense. In the middle, there will be trouble to every one whether biped or quadruped in the household. In the end, there may be ease and comfort.  Sloka 72. During the progress of the Sun's mahadasa occupying the depression Navamsa in its exaltation house, a person has to apprehend ill-fame, danger, the death of a son, a wife or some paternal relation and loss of property in connection with agriculture and other pursuits. But in the dasa of the same planet occupying the exaltation Navamsa in the depression house, the person concerned will attain regal prosperity, happiness, though towards the end thereof there may occur loss of wealth or his own demise.",
            hindi: "श्लोक 60. सूर्य के दासा की प्रगति के दौरान, ध्यान दिए जाने वाले सामान्य प्रभाव होंगे: चुपके से खनन और अन्य तरीकों से पैसा बनाना, आग और जानवरों से परेशानी, आंखों की सूजन, पेट और दांतों को प्रभावित करने वाली बीमारी, पत्नी और बच्चों से अलग होना, श्रद्धेय वरिष्ठ नागरिकों और माता - पिता के बीच नुकसान और नौकरों, काइन और संपत्ति के बीच सामान्य क्षय। श्लोक 71. सूर्य के दासा के प्रारंभिक भाग में, संबंधित व्यक्ति का पिता बीमार हो जाएगा, और बहुत अधिक खर्च होगा। बीच में, हर किसी को परेशानी होगी चाहे घर में बाईप किया गया हो या चौगुना। अंत में, आराम और सुकून हो सकता है। श्लोक 72. अपने उत्कर्ष गृह में अवसाद नवमसा पर कब्जा करने वाले सूर्य के महादास की प्रगति के दौरान, एक व्यक्ति को कृषि और अन्य कार्यों के संबंध में कुख्यात, खतरे, एक बेटे की मृत्यु, एक पत्नी या कुछ पैतृक संबंध और संपत्ति के नुकसान की आशंका होती है। लेकिन उसी ग्रह के दास में जो अवसादग्रस्तता के घर में नवमश की महिमा पर कब्जा कर रहा है, संबंधित व्यक्ति को शाही समृद्धि, खुशी प्राप्त होगी, हालांकि इसके अंत में धन की हानि या उसका स्वयं का निधन हो सकता है।",
        },
    },
    Moon: {
        BPHS: {
            english:
                "O Brahmin! After describing the effects of the Dasa of Sun in brief, I will now come to the effects of Vimshottari Dasa of Moon. During the Dasa of Moon from its commencement to the end there will be opulence and glory, good fortune, gain of wealth, auspicious functions at home, dawn of fortune, attainment of a high position in Government, acquisition of conveyances, clothes, birth of children and acquisition of cattle, should Moon be in her exaltation, in her own Rasi, in Kendra, in Labh, Dharm, or Putr, be associated with, or receives a Drishti from benefics, be fully powerful and is associated with the Lord of Karm, Dharm, or Bandhu. There will be extraordinary gains of wealth and luxuries, if such a Moon is in Dhana Bhava.  Should Moon be waning, or in her debilitation Rasi, there will be loss of wealth in her Dasa. If Moon is in Sahaj, there will be happiness off and on. If Moon is associated with malefics, there will be idiocy, mental tension, trouble from employees and mother and loss of wealth. If waning Moon is in Ari, Randhra, or Vyaya, or is associated with malefics, there will be inimical relations with Government, loss of wealth, distress to mother and similar evil effects. If a strong Moon is placed in Ari, Randhra, or Vyaya there will be troubles and good times off and on.",
            hindi: "हे ब्राह्मण! सूर्य के दास के प्रभावों का संक्षेप में वर्णन करने के बाद, अब मैं चंद्रमा के विमशोत्तरी दास के प्रभावों पर आऊंगा। चंद्रमा के दास के प्रारंभ से अंत तक समृद्धि और महिमा, सौभाग्य, धन की प्राप्ति, घर पर शुभ कार्य, भाग्य की भोर, सरकार में उच्च पद की प्राप्ति, संप्रेषण का अधिग्रहण, कपड़े, बच्चों का जन्म और मवेशियों का अधिग्रहण होगा, क्या चंद्रमा अपने उत्थान में होना चाहिए, अपनी राशि में, केंद्र में, लाभ में, धर्म, या पुत्र, लाभार्थियों से दृष्टि से जुड़ा हुआ है, या प्राप्त करता है, पूरी तरह से शक्तिशाली है और कर्म, धर्म या बंधु के प्रभु से जुड़ा हुआ है। धन और विलासिता का असाधारण लाभ होगा, अगर ऐसा चंद्रमा धना भव में है। यदि चंद्रमा कम हो रहा है, या उसकी दुर्बलता रासी में, उसके दास में धन की हानि होगी। यदि चंद्रमा सहज में है, तो खुशी बंद और चालू होगी। यदि चंद्रमा को मैलफिक्स से जोड़ा जाता है, तो मूर्खतापूर्ण, मानसिक तनाव होगा, कर्मचारियों और मां से परेशानी और धन की हानि। यदि चंद्रमा का ढलना अरी, रणधरा, या व्याया में होता है, या दुर्भावना से जुड़ा होता है, तो सरकार के साथ शत्रुतापूर्ण संबंध होंगे, धन की हानि होगी, मां को परेशानी होगी और इसी तरह के बुरे प्रभाव होंगे। यदि अरी, रणध्रा या व्याया में एक मजबूत चंद्रमा रखा जाता है तो परेशानी होगी और अच्छे समय की छुट्टी होगी।",
        },
        JatakaParijata: {
            english:
                "Sloka 73. During the progress of the Moon's mahadasa, a person will have access to sacred prayers, scripture and Brahmanas; he will exert fascination over young females, and secure to himself women, wealth and lands; he will have a profusion of flowers, cloths, ornaments, perfumes and various valuable objects of enjoyment; but if there be anything to check the Moon's strength, the effect on the person concerned will be that he will be poor and suffer from wind-disease.+  Sloka 83. The effect due to the bhava over which the Moon presides may come off in the commencement of its mahadasa; that due to the character of the sign representing the bhava as well as to the Moon's position will be seen in the middle; what is due to the aspect on the Moon of other planets and what affects the part of the body denoted by the bhava will appear towards the end of the mahadasa.",
            hindi: "श्लोक 73. चंद्रमा के महादास की प्रगति के दौरान, एक व्यक्ति को पवित्र प्रार्थनाओं, शास्त्रों और ब्राह्मणों तक पहुंच प्राप्त होगी; वह युवा महिलाओं पर आकर्षण करेगा, और अपने लिए महिलाओं, धन और भूमि को सुरक्षित करेगा; उसे फूलों, कपड़ों, गहनों, इत्रों और आनंद की विभिन्न मूल्यवान वस्तुओं की भरमार होगी; लेकिन अगर चंद्रमा की ताकत की जांच करने के लिए कुछ भी है, तो संबंधित व्यक्ति पर प्रभाव यह होगा कि वह गरीब होगा और पवन - रोग से पीड़ित होगा। + श्लोक 83। चंद्रमा जिस भाव पर अध्यक्षता करता है, उसका प्रभाव उसके महादास के प्रारंभ में आ सकता है; कि भाव का प्रतिनिधित्व करने वाले चिह्न के चरित्र के साथ - साथ चंद्रमा की स्थिति के कारण बीच में दिखाई देगा; अन्य ग्रहों के चंद्रमा पर पहलू के कारण क्या होता है और भाव द्वारा दर्शाए गए शरीर के हिस्से को क्या प्रभावित करता है, यह महादास के अंत में दिखाई देगा।",
        },
    },
    Mars: {
        BPHS: {
            english:
                "If Mars is in his exaltation, in his Multrikon, in his own Rasi, in Kendra, in Labh, or Dhana Bhava with strength, in a benefic Ańś (Navamsa) and is associated with a benefic, there will be during his Dasa acquisition of kingdom (attainment of a high administrative, or political position in Government, gain of wealth and land, recognition by Government), gain of wealth from foreign countries and acquisition of conveyances and ornaments. There will also be happiness and good relations with co-borns. If Mars with strength is placed in a Kendra, or in Sahaj, there will be gain of wealth through valour, victory over enemies, happiness from wife and children. There will, however, be a possibility of some unfavourable effects at the end of the Dasa.  If Mars is in his debilitation Rasi, weak, in an inauspicious Bhava, or is associated with, or receives a Drishti from malefics, there will be in his Dasa loss of wealth, distress and similar unfavourable effects.",
            hindi: "यदि मंगल अपने उत्कर्ष में है, अपने मल्टीकॉन में, अपने स्वयं के रासी में, केंद्र में, लाभ में, या धन भव में ताकत के साथ, एक लाभार्थी Aśś (नवमसा) में है और एक लाभार्थी के साथ जुड़ा हुआ है, तो उसके राज्य के दास अधिग्रहण (सरकार में एक उच्च प्रशासनिक, या राजनीतिक स्थिति की प्राप्ति, धन और भूमि का लाभ, सरकार द्वारा मान्यता), विदेशों से धन का लाभ और वाहन और गहने का अधिग्रहण होगा। सह - जन्मों के साथ खुशी और अच्छे संबंध भी होंगे। यदि बलवान मंगल को केंद्र में, या सहज में रखा जाए, तो वीरता, शत्रुओं पर विजय, पत्नी और बच्चों से सुख के माध्यम से धन लाभ होगा। हालांकि, दास के अंत में कुछ प्रतिकूल प्रभावों की संभावना होगी। यदि मंगल उसकी दुर्बलता में है, राशी कमजोर है, अशुभ भाव में है, या दुर्भावना से जुड़ा हुआ है, या उससे दृष्टि प्राप्त करता है, तो उसके दास में धन की हानि होगी, संकट और इसी तरह के प्रतिकूल प्रभाव।",
        },
        JatakaParijata: {
            english:
                "Sloka 84. Astrologers opine that in the ripening of Mars' mahadasa there may be attempts at money-making by taking to fire arms and by engaging in wars among rival kings and by other ways; there may be coming in of money also by medicine, by trickery, by fraud, and by diverse cruel acts; there may be suffering caused by fever arising from a morbid state of bile and blood; there will be seen a propensity on the part of the person concerned to resort continually to the society of low women and a crop of hatred emanating from sons, wife, relatives and reverend seniors. And in consequence of all this, the person will have to eat bad unwholesome food.  Sloka 94. At the out$et of Mars dasa, there will be humiliation and waste of wealth. In the middle of the dasa, there may be danger to be apprehended from rulers, fire, brigands, and the like; the same will happen also in the concluding portion of the dasa.  Sloka 95. If Mars occupy the depression Navamsa in its exaltation house, there will be according to the astrologers, death among the children and brothers of the person concerned, during the dasa of the planet. If it be in the house of depression and occupy the exaltation Navamsa, the effect will appear in the success of agriculture and other operations and in the accession to lands, wealth, grain and material comforts.",
            hindi: "श्लोक 84. ज्योतिषियों का मत है कि मंगल के महादास के पकने में हथियारों को आग लगाकर और प्रतिद्वंद्वी राजाओं के बीच युद्धों में शामिल होकर और अन्य तरीकों से पैसा बनाने के प्रयास हो सकते हैं; दवा, छल, धोखाधड़ी और विविध क्रूर कृत्यों से भी पैसे आ सकते हैं; पित्त और रक्त की रुग्ण स्थिति से उत्पन्न बुखार के कारण पीड़ा हो सकती है; निम्न महिलाओं के समाज का लगातार सहारा लेने के लिए संबंधित व्यक्ति की ओर से एक प्रवृत्ति दिखाई देगी और बेटों, पत्नी, रिश्तेदारों और आदरणीय वरिष्ठों से निकलने वाली नफरत की फसल। और इन सब के परिणामस्वरूप, व्यक्ति को बुरा अस्वास्थ्यकर भोजन खाना पड़ेगा। श्लोक 94. मंगल दास के बाहर$et पर, अपमान और धन की बर्बादी होगी। दास के बीच में, शासकों, अग्निशमन, ब्रिगेड और इसी तरह से पकड़े जाने का खतरा हो सकता है; दास के समापन भाग में भी ऐसा ही होगा। श्लोक 95. यदि मंगल अपने उत्कर्ष गृह में अवसाद नवमसा पर कब्जा कर लेता है, ज्योतिषियों के अनुसार, ग्रह के दासा के दौरान संबंधित व्यक्ति के बच्चों और भाइयों के बीच मृत्यु होगी। यदि यह अवसाद के घर में है और उत्कर्ष नवमसा पर कब्जा कर लेता है, तो इसका प्रभाव कृषि और अन्य कार्यों की सफलता में और भूमि, धन, अनाज और भौतिक सुख - सुविधाओं के प्रवेश में दिखाई देगा।",
        },
    },
    Rahu: {
        BPHS: {
            english:
                "In order to clarify the effects of the Dasa of Rahu I shall first mention the exaltation and debilitation Rāśis of Rahu and Ketu. The exaltation Rasi of Rahu is Vrishabh. The exaltation Rasi of Ketu is Vrischik. The Multrikonas of Rahu and Ketu are Mithun and Dhanu. The own Rāśis of Rahu and Ketu are Kumbh and Vrischik. Some sages have expressed the view, that Kanya is the own Rasi of Rahu and Meen is the own Rasi of Ketu. Should Rahu be in his exaltation Rasi etc., there will be during the Dasa of Rahu great happiness from acquisition of wealth, agricultural products etc., acquisition of conveyances with the help of friends and Government, construction of a new house, birth of sons (children), religious inclinations, recognition from Government of foreign countries and gain of wealth, clothes etc. If Rahu be associated with, or receives a Drishti from benefics, be in a benefic Rasi and be in Tanu, Bandhu, Yuvati, Karm, Labh, or Sahaj, there will be during his Dasa all kinds of comforts by the beneficence of the Government, acquisition of wealth through a foreign Government, or sovereign and felicity at home.  If Rahu is in Randhra, or Vyaya Bhava, there will be during his Dasa all kinds of troubles and distress. If Rahu is associated with a malefic, or a Marak Grah, or is in his debilitation Rasi, there will be loss of position, destruction of his residential house, mental agony, trouble to wife and children and misfortune of getting bad food. There will be loss of wealth at the commencement of the Dasa, some relief and gain of wealth in his own country and distress and anxieties during the last portion of the Dasa.",
            hindi: "राहु के दास के प्रभावों को स्पष्ट करने के लिए मैं सबसे पहले राहु और केतु के उत्थान और दुर्बलता राशियों का उल्लेख करूंगा। राहु का उत्कर्ष रासी वृषभ है। केतु का उत्कर्ष रासी वृश्चिक है। राहु और केतु के बहुकोण मिथुन और धनु हैं। राहु और केतु के स्वयं के राशी कुंभ और वृश्चिक हैं। कुछ ऋषियों ने यह विचार व्यक्त किया है कि कन्या राहु की स्वयं की रासी है और मीन केतु की स्वयं की रासी है। क्या राहु को अपने उत्थान रासी आदि में होना चाहिए, राहु के दास के दौरान धन, कृषि उत्पादों आदि के अधिग्रहण से बहुत खुशी होगी, मित्रों और सरकार की मदद से संप्रेषण का अधिग्रहण होगा, एक नया घर का निर्माण होगा, बेटों (बच्चों) का जन्म होगा, धार्मिक झुकाव होगा, विदेशों की सरकार से मान्यता होगी और धन, कपड़े आदि का लाभ होगा। यदि राहु लाभार्थियों से जुड़ा हुआ है, या दृष्टि प्राप्त करता है, तो लाभकारी राशी में हो और तनु, बंधु, युवति, कर्म, लाभ, या सहज में हो, उसके दास के दौरान सरकार के उपकार, विदेशी सरकार के माध्यम से धन का अधिग्रहण, या घर पर संप्रभुता और प्रसन्नता से सभी प्रकार की सुविधाएं होंगी। यदि राहु रणध्रा, या व्यय भाव में है, तो उसके दास के दौरान सभी प्रकार की परेशानियां और संकट होंगे। यदि राहु किसी दुष्ट, या मरक ग्रह से जुड़ा हुआ है, या उसकी दुर्बलता रासी में है, तो स्थिति का नुकसान होगा, उसके आवासीय घर का विनाश होगा, मानसिक पीड़ा होगी, पत्नी और बच्चों के लिए परेशानी और खराब भोजन पाने का दुर्भाग्य। दास के आरंभ में धन की हानि होगी, अपने ही देश में कुछ राहत और धन की प्राप्ति होगी और दास के अंतिम भाग के दौरान संकट और चिंताओं का सामना करना पड़ेगा।",
        },
        JatakaParijata: {
            english:
                "Sloka 96. Loss of such things as comfort, happiness, wealrh and worldly status, the pang of parting with a wife, children and relatives, illness in the extreme, residence in a strange land, and a disposition to wrangle are what Rahu brings about.  Sloka 106. Rahu occupying Cancer, Taurus or Aries, say the astrologers, will secure to the person concerned during the ripening of its dasa wealth and corn, edification and amusement, honor from the sovereign, wives, servants and dependants happy and well-off.  Sloka 107. Astrologers say that Rahu in Kanya, Meena, or Dhanus gives to the person concerned during its dasa wife and children, lordship of lands and a carriage drawn by men. All these are liable to be lost at the conclusion of the dasa.  Sloka 108. When Rahu is in Leo, Virgo or Cancer, a person becomes a king or a king's peer during the ripening of its dasa; he wilt command an army composed of elephants and horses, will be highly beneficent, exceedingly wealthy, devoted to pleasure and dearly attached to his wife and children.  Sloka 109. At the outset of Rahu dasa, a person suffers distress; in the middle of it, he may have much enjoyment; but in the end, he may become bereaved of his parents and even lose his status.",
            hindi: "श्लोक 96. आराम, खुशी, सुख और सांसारिक स्थिति जैसी चीजों का नुकसान, पत्नी, बच्चों और रिश्तेदारों के साथ बिदाई का दर्द, चरम में बीमारी, एक अजीब भूमि में निवास, और झगड़ा करने का स्वभाव राहु लाता है। श्लोक 106. ज्योतिषियों का कहना है कि कर्क, वृषभ या मेष राशि पर कब्जा करने वाला राहु, अपने दास धन और मक्का के पकने, उन्नयन और मनोरंजन, संप्रभु, पत्नियों से सम्मान के दौरान संबंधित व्यक्ति को सुरक्षित करेगा, नौकर और आश्रित खुश और खुश हैं। श्लोक 107. ज्योतिषियों का कहना है कि कन्या, मीना, या धनु में राहु अपनी दासा पत्नी और बच्चों, भूमि के आधिपत्य और पुरुषों द्वारा खींची गई गाड़ी के दौरान संबंधित व्यक्ति को देता है। ये सभी दास के समापन पर खो जाने के लिए उत्तरदायी हैं। श्लोक 108. जब राहु सिंह, कन्या या कर्क राशि में होता है, तो कोई व्यक्ति अपने दासा के पकने के दौरान राजा या राजा का सहकर्मी बन जाता है; वह हाथियों और घोड़ों से बनी सेना को आदेश देगा, अत्यधिक लाभकारी होगा, अत्यधिक धनवान, आनंद के लिए समर्पित और अपनी पत्नी और बच्चों से बहुत जुड़ा हुआ। श्लोक 109. राहुदास की शुरुआत में, एक व्यक्ति संकट से पीड़ित होता है; इसके बीच में, वह बहुत आनंद ले सकता है; लेकिन अंत में, वह अपने माता - पिता से शोकित हो सकता है और यहां तक कि अपनी स्थिति भी खो सकता है।",
        },
    },
    Jupiter: {
        BPHS: {
            english:
                "Now I am going to describe the effects of the Dasa of Jupiter, the great benefic and preceptor of the Gods.  If Jupiter is in his exaltation, his own Rasi, his Multrikon, in Karm, Putr, or Dharm Bhava, in his own Navamsa, or in his exalted Navamsa, there will be during his Dasa: acquisition of kingdom, great felicity, recognition by Government, acquisition of conveyances and clothes, devotion to deities and Brahmins, happiness in respect of his wife and children and success in the performance of religious sacrifices (oblations).  If Jupiter is in his debilitation Rasi, combust, associated with malefics, or in Ari, or Randhra, there will be during his Dasa loss of residential premises, anxiety, distress to children, loss of cattle and pilgrimage. The Dasa will give some unfavourable effects at its commencement only. During the later part of the Dasa there will be good effects, like gain of wealth, awards from and recognition by Government.",
            hindi: "अब मैं देवताओं के महान हितकारी और उपदेशक बृहस्पति के दास के प्रभावों का वर्णन करने जा रहा हूं। यदि बृहस्पति अपने उत्कर्ष में है, तो उसका अपना रासी, उसका बहुकोण, कर्म, पुत्र, या धर्म भाव में, अपने स्वयं के नवमश में, या अपने उच्च नवमश में, उसके दास के दौरान होगा: राज्य का अधिग्रहण, महान सम्मान, सरकार द्वारा मान्यता, संप्रेषण और कपड़े का अधिग्रहण, देवताओं और ब्राह्मणों के प्रति भक्ति, अपनी पत्नी और बच्चों के संबंध में खुशी और धार्मिक बलिदान (बलिदान) के प्रदर्शन में सफलता। यदि बृहस्पति अपनी दुर्बलता में है रासी, दहन, नरफिक्स से जुड़ा हुआ है, या अरी, या रणधरा में है, तो उसके दासा के दौरान आवासीय परिसर, चिंता, बच्चों के लिए संकट, मवेशियों और तीर्थयात्रा का नुकसान होगा। दास अपने प्रारंभ में ही कुछ प्रतिकूल प्रभाव देगा। दास के बाद के भाग के दौरान अच्छे प्रभाव होंगे, जैसे धन की प्राप्ति, सरकार की ओर से पुरस्कार और मान्यता।",
        },
        JatakaParijata: {
            english:
                "Sloka 110. Jupiter secures to the person concerned, during its dasa, rank, wealth, vehicle, apparel, royal good will, purity of heart, power, knowledge, practice corresponding thereto, wife, children and all else connected therewith.  Sloka 120. Jupiter occupying a depression Navamsa in its exaltation sign brings on during the progress of its dasa danger through robbers, foes and rulers, the hatred of wife and sons and bad luck generally; but when the planet is in the exaltation Navamsa in its depression sign, it secures during its dasa to the person concerned, royal favor, material comforts, learning, wisdom, fame, wealth and the influence which such things carry; and it may even be the lordship of the whole country.",
            hindi: "श्लोक 110. बृहस्पति अपने दासा, रैंक, धन, वाहन, परिधान, शाही सद्भावना, हृदय की शुद्धता, शक्ति, ज्ञान, उससे संबंधित अभ्यास, पत्नी, बच्चों और उससे जुड़े अन्य सभी के दौरान संबंधित व्यक्ति को सुरक्षित करता है। श्लोक 120. बृहस्पति अपने उत्कर्ष चिन्ह में एक अवसाद पर कब्जा कर रहा है नवमसा अपने डासा खतरे की प्रगति के दौरान लुटेरों, दुश्मनों और शासकों के माध्यम से लाता है, पत्नी और बेटों की नफरत और आम तौर पर दुर्भाग्य; लेकिन जब ग्रह अपने अवसाद के संकेत में नवमसा की बड़ाई में होता है, तो यह अपने दासा के दौरान संबंधित व्यक्ति, शाही पक्ष, भौतिक सुख, सीखने, ज्ञान, प्रसिद्धि, धन और उस प्रभाव को सुरक्षित करता है जो ऐसी चीजें ले जाती हैं; और यह पूरे देश का प्रभुत्व भी हो सकता है।",
        },
    },
    Saturn: {
        BPHS: {
            english:
                "Now I will describe to you the effects of the Dasa of Saturn, who is considered the vilest and most inferior amongst all the Grahas.  If Saturn is in his exaltation, in his own Rasi, or in Multrikon, or friendly Rasi, in his own, or exalted Navamsa and in Sahaj, or Labh, there will be during his Dasa recognition by Government, opulence and glory, name and fame, success in the educational sphere, acquisition of conveyances and ornaments etc., gain of wealth, favours from Government, attainment of a high position, like Commander of an Army, acquisition of a kingdom, benevolence of goddess Lakshmi, gain of property and birth of children.  If Saturn is in Ari, Randhra, or Vyaya, in his debilitation Rasi, or combust, there will be during his Dasa ill effects from poison, injury from weapons, separation from father, distress to wife and children, disaster, as a result of displeasure of Government, imprisonment etc. If Saturn receives a Drishti from, or is associated with a benefic, is placed in a Kendra, or in a Trikona, in Dhanu, or in Meen, there will be acquisition of a kingdom, conveyances and clothes.",
            hindi: "अब मैं आपको शनि के दास के प्रभावों का वर्णन करूंगा, जिसे सभी ग्रहों में सबसे नीच और सबसे नीच माना जाता है। यदि शनि अपने स्वयं के राशी में, या मल्टीकॉन में, या मैत्रीपूर्ण रासी में, अपने स्वयं के, या ऊंचे नवमसा में और सहज, या लाभ में अपने उत्थान में है, तो सरकार द्वारा उनकी दास मान्यता, समृद्धि और महिमा, नाम और प्रसिद्धि, शैक्षिक क्षेत्र में सफलता, संप्रेषण और गहने आदि का अधिग्रहण, धन का लाभ, सरकार से अनुग्रह, एक उच्च पद की प्राप्ति, जैसे सेना का कमांडर, एक राज्य का अधिग्रहण, देवी लक्ष्मी की परोपकार, संपत्ति का लाभ और बच्चों का जन्म। यदि शनि अपनी दुर्बलता रासी, या दहन में अरी, रणध्रा, या व्याया में है, तो उसके दास के दौरान जहर, हथियारों से चोट, पिता से जुदाई, पत्नी और बच्चों के लिए संकट, आपदा, सरकार की नाराजगी, कारावास आदि के परिणामस्वरूप दुष्प्रभाव होंगे। यदि शनि से दृष्टि प्राप्त करता है, या एक लाभार्थी के साथ जुड़ा हुआ है, एक केंद्र में रखा गया है, या त्रिकोणा में, धनु में, या मीन में, एक राज्य, वाहन और कपड़े का अधिग्रहण होगा।",
        },
        JatakaParijata: {
            english:
                "Sloka 121. Astrologers declare that during dasa of Saturn, a person may come into possession of goats, asses, camels, old women, birds and coarse grain and get wealth by the administration of a guild,  township or village community and become the ruler of a low tribe.  Sloka 132. Saturn occupying the depression Navamsa in its exaltation house produces happiness at the commencement of its dasa, but towards the end, it is fraught with woe to the creatures concerned. If the planet occupy the exaltation Navamsa in its depression house, the end of the dasa is happy while in the initial portion there may be evil to be feared from robbers and enemies, much misery and roaming in foreign lands.",
            hindi: "श्लोक 121. ज्योतिषी घोषणा करते हैं कि शनि के दास के दौरान, एक व्यक्ति बकरियों, गधों, ऊंटों, वृद्ध महिलाओं, पक्षियों और मोटे अनाज के कब्जे में आ सकता है और एक गिल्ड, टाउनशिप या ग्राम समुदाय के प्रशासन द्वारा धन प्राप्त कर सकता है और एक निम्न जनजाति का शासक बन सकता है। श्लोक 132. अपने उत्कर्ष गृह में अवसाद नवमश पर कब्जा करने वाला शनि अपने दासा के प्रारंभ में खुशी पैदा करता है, लेकिन अंत में, यह संबंधित प्राणियों के लिए दुख से भरा होता है। यदि ग्रह अपने अवसादग्रस्तता वाले घर में नवमसा के उत्कर्ष पर कब्जा कर लेता है, तो दास का अंत खुश होता है जबकि प्रारंभिक भाग में लुटेरों और दुश्मनों से डरने के लिए बुराई हो सकती है, बहुत दुख और विदेशी भूमि में घूमना हो सकता है।",
        },
    },
    Mercury: {
        BPHS: {
            english:
                "Now I am going to describe the effects of the Dasa of Mercury, who is called a Kumar (in his teens) amongst all the Grahas.  If Mercury is in his exaltation, in his own, in a friendly Rasi, or in Labh, Putr, or Dharm, there will be during his Dasa acquisition of wealth, gain of reputation, improvement in knowledge, benevolence of Government, auspicious functions, happiness from wife and children, good health, availability of sweetish preparations, profits in business etc. If Mercury receives a Drishti from a benefic, is in Dharm, or is the Lord of Karm, the aforesaid beneficial results will be experienced in full and there will be great felicity all-round.  If Mercury is associated with a malefic, there will be during his Dasa punishment by Government, inimical relations with kinsmen, journey to a foreign country, dependence on others and the possibility of urinary troubles. If Mercury is in Ari, Randhra, or Vyaya, there will be loss of wealth, due to indulgence in lascivious activities, possibility of suffering from rheumatism and jaundice, danger of thefts and malevolence of Government, loss of land and cattle etc. At the commencement of the Dasa of Mercury, there will be gains of wealth, betterment in the educational sphere, birth of children and happiness. In the middle of the Dasa, there will be recognition from Government. The last part of the Dasa will be distressful.",
            hindi: "अब मैं बुध की दशा के प्रभावों का वर्णन करने जा रहा हूँ, जिन्हें सभी ग्रहों में कुमार (किशोरावस्था) कहा जाता है। यदि बुध अपनी उच्च राशि में, अपनी ही राशि में, मित्र राशि में, या लाभ, पुत्र या धर्म में हो, तो उसकी दशा में धन प्राप्ति, प्रतिष्ठा में वृद्धि, ज्ञान में वृद्धि, सरकार की कृपा, शुभ कार्य, पत्नी और बच्चों से सुख, अच्छा स्वास्थ्य, मिष्ठान्नों की उपलब्धता, व्यापार में लाभ आदि होंगे। यदि बुध पर किसी शुभ ग्रह की दृष्टि हो, वह धर्म में हो, या कर्मेश हो, तो उपरोक्त लाभकारी परिणाम पूर्ण रूप से अनुभव किए जाएँगे और सर्वत्र अपार सुख-समृद्धि होगी। यदि बुध किसी पाप ग्रह से युक्त हो, तो उसकी दशा में सरकार द्वारा दंड, स्वजनों से शत्रुतापूर्ण संबंध, विदेश यात्रा, दूसरों पर निर्भरता और मूत्र संबंधी समस्याओं की संभावना होगी। यदि बुध अरी, रंध्र या व्यय भाव में हो, तो कामुक कार्यों में लिप्त होने के कारण धन की हानि, गठिया और पीलिया रोग की संभावना, चोरी का भय और सरकारी द्वेष, भूमि और पशुधन की हानि आदि होगी। बुध की दशा के आरंभ में धन लाभ, शिक्षा के क्षेत्र में उन्नति, संतान प्राप्ति और सुख की प्राप्ति होगी। दशा के मध्य में सरकार से मान्यता मिलेगी। दशा का अंतिम भाग कष्टकारी होगा।",
        },
        JatakaParijata: {
            english:
                "Sloka 133. During the period that Mercury's influence takes effect, a person will earn money through the instrumentality of reverend seniors, relatives and friends; he will have fame and happiness; he will go on an embassy, derive an income by dealing in gold ware and suffer from wind ailment.  Sloka 143. Mercury occupying the depression Navamsa in its exaltation sign, produces incompetency for work in the person concerned and makes him indigent in its dasa.  Sloka 144. Mercury in depression but in the exaltation Navamsa ordains prosperity in the end of its dasa though in the beginning thereof all be barren of effect.",
            hindi: "श्लोक 133. बुध के प्रभाव काल में, व्यक्ति पूज्य वरिष्ठजनों, सगे-संबंधियों और मित्रों के सहयोग से धन अर्जित करता है; यश और सुख प्राप्त करता है; दूतावास जाता है, स्वर्ण-वस्तुओं का व्यापार करता है और वायु रोग से पीड़ित होता है। श्लोक 143. यदि बुध अपनी उच्च राशि में अवनति नवांश में स्थित हो, तो वह व्यक्ति में कार्य करने की अयोग्यता उत्पन्न करता है और अपनी दशा में उसे दरिद्र बनाता है। श्लोक 144. यदि बुध अवनति किन्तु उच्च नवांश में हो, तो अपनी दशा के अंत में समृद्धि प्रदान करता है, यद्यपि उसकी शुरुआत में सब कुछ प्रभावहीन होता है।",
        },
    },
    Ketu: {
        BPHS: {
            english:
                "Now I will tell you about the Dasa of Ketu, who is a headless trunk (Kabandha) amongst all the Grahas.  If Ketu is in a Kendra, a Trikona, or in Labh, in a benefic Rasi, in his exaltation, or in his own Rasi, there will be during his Dasa cordial relations with the king, desired headship of a country, or village, comforts of conveyances, happiness from children, gain from foreign countries, happiness from wife and acquisition of cattle. If Ketu is in Sahaj, Ari, or Labh, there will be in his Dasa acquisition of a kingdom, good relations with friends and opportunities for the acquisition of elephants. At the commencement of the Ketu Dasa there will be Raj Yog. During the middle portion of the Dasa there will be possibilities of fearfulness and in the last part there will be sufferings from ailments and journeys to distant places. If Ketu is in Dhana, Randhra, or Vyaya, or receives a Drishti from a malefic, there will be imprisonment, destruction of kinsmen and residential premises and anxieties, company of menials and diseases.",
            hindi: "अब मैं आपको केतु की दशा के बारे में बताता हूँ, जो सभी ग्रहों में कबंध है। यदि केतु केंद्र, त्रिकोण, लाभ, शुभ राशि, उच्च या अपनी ही राशि में हो, तो उसकी दशा में राजा के साथ मधुर संबंध, देश या गाँव का मनचाहा मुखियापन, वाहन सुख, संतान सुख, विदेश से लाभ, पत्नी सुख और पशु प्राप्ति होगी। यदि केतु सहज, अरि या लाभ राशि में हो, तो उसकी दशा में राज्य प्राप्ति, मित्रों से मधुर संबंध और हाथी प्राप्ति के अवसर प्राप्त होंगे। केतु दशा के आरंभ में राजयोग होगा। दशा के मध्य भाग में भय की संभावना रहेगी और अंत में रोगों से कष्ट और दूर स्थानों की यात्राएँ होंगी। यदि केतु धन, रंध्र या व्यय भाव में हो या पाप ग्रह की दृष्टि हो तो कारावास, स्वजनों और आवास का नाश, चिंता, दासों का साथ और रोग होंगे।",
        },
        JatakaParijata: {
            english:
                "Sloka 145. At the time of Ketu's influence begins to ripen and yield fruit, a person feels distressed; his sense and judgment fail; he becomes afflicted with various diseases; his physical torments grow; his evil acts multiply; his life is one of great misery. His comforts, if any, are but slight.  Sloka 155. Ketu associated with a benefic planet yields happiness in its dasa. If aspected by a benefic planet, it leads to the acquisition of abundant wealth.  Sloka 156. When associated with malefic planets, Ketu produces danger throuqh the instrumentality of wicked men and misery through acquired diseases leading to waste of wealth.  Sloka 157. Three-fold is the effect of Ketu's dasa. At the beginning of it, elders and relations are taken ill; in the middle of it, there is money coming in; at the end there is happiness.",
            hindi: "श्लोक 145. केतु के प्रभाव के समय जब जातक परिपक्व होकर फल देने लगता है, तो व्यक्ति व्यथित महसूस करता है; उसकी इंद्रियां और निर्णय शक्ति विफल हो जाती है; वह विभिन्न रोगों से ग्रस्त हो जाता है; उसकी शारीरिक पीड़ाएं बढ़ जाती हैं; उसके बुरे कर्म बढ़ जाते हैं; उसका जीवन महान दुखों से भरा होता है। उसके सुख, यदि कोई हों, तो बहुत कम होते हैं। श्लोक 155. शुभ ग्रह से युक्त केतु अपनी दशा में सुख प्रदान करता है। यदि शुभ ग्रह से दृष्ट हो, तो यह प्रचुर धन प्राप्ति कराता है। श्लोक 156. पाप ग्रहों से युक्त होने पर, केतु दुष्ट पुरुषों के माध्यम से खतरा और धन की बर्बादी करने वाली बीमारियों के माध्यम से दुख उत्पन्न करता है। श्लोक 157. केतु की दशा का प्रभाव तीन गुना होता है। इसकी शुरुआत में, बुजुर्ग और रिश्तेदार बीमार पड़ते हैं",
        },
    },
    Venus: {
        BPHS: {
            english:
                "Now I will describe the effects of the Dasa of Venus, who is the incarnate of intoxication, ecstasy, delight and pride amongst all the Grahas.  If Venus is in his exaltation, in his own Rasi, or in a Kendra, or a Trikona, there will be during his Dasa acquisition of fancy clothes, ornaments, conveyances, cattle and land etc., availability of sweet preparations every day, recognition from the sovereign, luxurious functions of songs and dances etc. by the benevolence of Goddess Lakshmi. If Venus is in his Multrikon, during his Dasa there will definitely be acquisition of a kingdom, acquisition of a house, birth of children and grandchildren, celebration of marriage in the family, attainment of a high position, like the Commander of an Army, visits of friends, recovery of lost wealth, property, or kingdom.  If Venus is in Ari, Randhra, or Vyaya, there will be during his Dasa inimical relations with kinsmen, distress to wife, losses in business, destruction of cattle and separation from relations.  If Venus is in Bandhu, as Lord of Dharm, or Karm, there will be during his Dasa attainment of rulership of a country, or village, performance of pious deeds, like building of reservoirs and temples and giving grains etc. in charity, availability of sweet preparations every day, vigor in work, name and fame and happiness from wife and children.  Similar are the effects of Venus in his sub-periods. If Venus is Lord of Dhana, or Yuvati, there will be during his Dasa physical pains and troubles. To get alleviation from those troubles the native should perform Shatarudriya, or Mrityunjaya Japa in the prescribed manner and give in charity a cow, or female buffalo.",
            hindi: "अब मैं शुक्र की दशा के प्रभावों का वर्णन करूँगा, जो सभी ग्रहों में मद, उल्लास, प्रसन्नता और गर्व के अवतार हैं। यदि शुक्र अपनी उच्च राशि में, अपनी ही राशि में, या केंद्र या त्रिकोण में हो, तो उसकी दशा में सुंदर वस्त्र, आभूषण, वाहन, पशु और भूमि आदि की प्राप्ति, प्रतिदिन मिष्ठान्नों की प्राप्ति, राजा से सम्मान, देवी लक्ष्मी की कृपा से गीत-नृत्य आदि के भव्य आयोजन होंगे। यदि शुक्र अपने मूलत्रिकोण में हो, तो उसकी दशा में निश्चित रूप से राज्य प्राप्ति, भवन प्राप्ति, संतान और पौत्र-पौत्रियों का जन्म, परिवार में विवाह उत्सव, सेनापति जैसे उच्च पद की प्राप्ति, मित्रों के आगमन, खोई हुई संपत्ति, संपत्ति या राज्य की प्राप्ति होगी। यदि शुक्र अरी, रंध्र या व्यय में हो, तो उसकी दशा में स्वजनों से शत्रुतापूर्ण संबंध, पत्नी को कष्ट, व्यापार में हानि, पशुधन का नाश और संबंधियों से वियोग होगा। यदि शुक्र बंधु राशि में धर्म या कर्म का स्वामी होकर स्थित हो, तो उसकी दशा में किसी देश या गाँव का शासन प्राप्त होगा, जलाशयों और मंदिरों का निर्माण और अन्न आदि का दान जैसे पुण्य कार्य संपन्न होंगे, प्रतिदिन मिष्ठान्न उपलब्ध होंगे, कार्य में उत्साह, यश और यश की प्राप्ति होगी, तथा पत्नी और संतान से सुख प्राप्त होगा। शुक्र की अन्तर्दशा में भी यही प्रभाव होता है। यदि शुक्र धन या युवती का स्वामी हो, तो उसकी दशा में शारीरिक कष्ट और परेशानियाँ होंगी। इन परेशानियों से मुक्ति पाने के लिए जातक को विधिपूर्वक शतरुद्रिय या मृत्युंजय जप करना चाहिए और गाय या भैंस दान में देनी चाहिए।",
        },
        JatakaParijata: {
            english:
                "Sloka 158. Venus in its dasa leads to the aquisition of wife, children, wealth, exceeding comfort, fragrant wreaths, apparel, ornaments, vehicles and other means of locomotion, fortune and fame equal to a king's.  Sloka 168. Venus in its exaltation sign but in the depression Navamsa causes loss of wealth and loss of status in its dasa.  Sloka 169. Venus in its depression sign but in the exaltation Navamsa gives to the person concerned during the ripening of its dasa, (success in) agriculture and trade and accession to his wealth.",
            hindi: "श्लोक 158. शुक्र अपनी दशा में पत्नी, संतान, धन, अत्यधिक सुख-सुविधाएँ, सुगंधित पुष्पमालाएँ, वस्त्र, आभूषण, वाहन और अन्य आवागमन के साधन, राजा के समान धन और यश की प्राप्ति कराता है। श्लोक 168. शुक्र अपनी उच्च राशि में किन्तु अवनति नवांश में हो तो अपनी दशा में धन और पद की हानि होती है। श्लोक 169. शुक्र अपनी अवनति राशि में किन्तु उच्च नवांश में हो तो अपनी दशा के दौरान संबंधित व्यक्ति को कृषि और व्यापार में सफलता और धन में वृद्धि प्रदान करता है।",
        },
    },
};
