/** Checks if a string is a valid Ayanamsa name. */
export const ayanamsaNames = [
    "Lahiri",
    "Fagan/Bradley",
    "De Luce",
    "Raman",
    "Usha/Shashi",
    "Krishnamurti",
    "Djwhal Khul",
    "Yukteshwar",
    "J.N. Bhasin",
    "Babylonian/Kugler 1",
    "Babylonian/Kugler 2",
    "Babylonian/Kugler 3",
    "Babylonian/Huber",
    "Babylonian/Eta Piscium",
    "Babylonian/Aldebaran = 15 Tau",
    "Hipparchos",
    "Sassanian",
    "Galact. Center = 0 Sag",
    "J2000",
    "J1900",
    "B1950",
    "Suryasiddhanta",
    "Suryasiddhanta, mean Sun",
    "Aryabhata",
    "Aryabhata, mean Sun",
    "SS Revati",
    "SS Citra",
    "True Citra",
    "True Revati",
    "True Pushya (PVRN Rao)",
    "Galactic Center (Gil Brand)",
    "Galactic Equator (IAU1958)",
    "Galactic Equator",
    "Galactic Equator mid-Mula",
    "Skydram (Mardyks)",
    "True Mula (Chandra Hari)",
    "Dhruva/Gal.Center/Mula (Wilhelm)",
    "Aryabhata 522",
    "Babylonian/Britton",
    "Vedic/Sheoran",
    "Cochrane (Gal.Center = 0 Cap)",
    "Galactic Equator (Fiorenza)",
    "Vettius Valens",
    "Lahiri 1940",
    "Lahiri VP285",
    "Krishnamurti-Senthilathiban",
    "Lahiri ICRC",
];
